version: "3.9"
services:

  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
    - published: 2080
      target: 80
    environment:
      TZ: America/Los_Angeles
    links:
    - db
    - fpm
    volumes:
    - .:/var/www/api
    - ./resources/web/site.conf:/etc/nginx/conf.d/default.conf

  fpm:
    build: .
    restart: unless-stopped
    environment:
      TZ: America/Los_Angeles
      docker: "true"
      MYSQL_DATABASE: Website
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
    - .:/var/www/api

  db:
    image: mariadb:latest
    restart: unless-stopped
    ports:
    - published: 2306
      target: 3306
    environment:
      TZ: America/Los_Angeles
      MYSQL_DATABASE: Website
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - db:/var/lib/mysql
    - ./resources/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./resources/db/init.sql:/docker-entrypoint-initdb.d/db-init.sql

volumes:
  db: {}
