version: "3.9"
services:

  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
    - 2080:80
    environment:
      TZ: ${TZ}
    depends_on:
    - db
    - fpm
    volumes:
    - .:/var/www/api
    - ./docker/web/site.conf:/etc/nginx/conf.d/default.conf

  fpm:
    build: .
    restart: unless-stopped
    environment:
      docker: 1
      TZ: ${TZ}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - .:/var/www/api

  db:
    image: mariadb:latest
    restart: unless-stopped
    ports:
    - 2306:3306
    environment:
      TZ: America/Los_Angeles
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
    - db:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/init.sql:/docker-entrypoint-initdb.d/db-init.sql

volumes:
  db: {}
