version: "3.8"
services:

  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
    - 2080:80
    environment:
      TZ: ${TZ}
    depends_on:
    - db
    - fpm
    volumes:
    - .:/var/www/api
    - ./docker/web/site.conf:/etc/nginx/conf.d/default.conf

  fpm:
    build: .
    restart: unless-stopped
    environment:
      docker: 1
      TZ: ${TZ}'
      API_KEY: ${API_KEY}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - .:/var/www/api

  db:
    image: mariadb:latest
    restart: unless-stopped
    ports:
    - 2306:3306
    environment:
      TZ: America/Los_Angeles
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      API_KEY: ${API_KEY}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
    - db:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  db: {}
